---
- name: installing required packages
  apt:
    name: dirmngr,gnupg,apt-transport-https,ca-certificates,build-essential

- name: installing (additional) required packages
  apt:
    name: curl,imagemagick

- name: adding gpg key for rvm
  shell: |
    apt-key adv --keyserver hkps://keys.openpgp.org --no-tty --recv 409B6B1796C275462A1703113804BB82D39DC0E3
    apt-key adv --keyserver hkps://keys.openpgp.org --no-tty --recv 7D2BAF1CF37B13E2069D6956105BD0E739499BDB

- name: installing rvm
  shell: "curl -sSL https://get.rvm.io | bash -s stable"
  args:
    warn: no

- name: "updating the {{ deploy_user }} user for rvm"
  user:
    name: "{{ deploy_user }}"
    append: yes
    groups: rvm
    shell: /bin/bash
    password_lock: yes

- name: creating /etc/profile.d/rvm_secure_path.sh
  copy:
    dest: /etc/profile.d/rvm_secure_path.sh
    content: "export rvmsudo_secure_path=1"

- name: "installing ruby {{ rvm_ruby }} via rvm"
  shell: "source /etc/profile.d/rvm.sh; rvm install ruby-{{ rvm_ruby }}"
  args:
    executable: /bin/bash

- name: "setting ruby {{ rvm_ruby }} as default via rvm"
  shell: "source /etc/profile.d/rvm.sh; rvm --default use ruby-{{ rvm_ruby }}"
  args:
    executable: /bin/bash

- name: "(re)installing bundler"
  shell: "source /etc/profile.d/rvm.sh; gem install bundler"
  args:
    executable: /bin/bash

- name: preparing installation of nodejs
  shell: "curl --fail -sSL -o setup-nodejs https://deb.nodesource.com/setup_{{ service.nodejs }}.x && bash setup-nodejs"
  args:
    warn: no

- name: installing nodejs and libv8
  apt:
    name: nodejs,libv8-dev

- name: installing pinned wkhtmltox
  apt:
    deb: https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-1/wkhtmltox_0.12.6-1.stretch_amd64.deb

- name: installing yarn repo key, repo and package
  shell: |
    curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
    echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
    apt-get update && apt-get install -y yarn
