---
- name: validating your ansible version
  assert:
    that: "ansible_version.full is version_compare('2.7', '>=')"
    msg: "OOPS, you need at least ansible 2.7.0 to run automate"

- name: validating target OS
  assert:
    that: service.os == ansible_distribution
    msg: "OOPS, unfortunately target OS/{{ ansible_distribution }} is not supported/{{ service.os }}"

- name: checking the existence of (local) rvm
  connection: local
  shell: which rvm

- name: updating (local) rvm
  connection: local
  shell: rvm get head

- name: on a Mac with brew? installing node & mysql & imagemagick
  connection: local
  shell: which brew && brew install node mysql imagemagick || true
