
- name: "populating required directories for {{ app.name }}"
  include_tasks: dirs.yml

- set_fact: releasenow="{{ ansible_date_time.iso8601_basic_short }}"

- name: "cloning in place the repository for {{ app.name }}"
  git:
    force: yes
    depth: 1
    repo: "{{ app.repo }}"
    ssh_opts: "-o StrictHostKeyChecking=no"
    version: "{{ app.branch | default('master') }}"
    dest: "{{ appshome }}/{{ app.name }}/releases/{{ releasenow }}"

- name: "pruning older {{ app.name }} releases, minus the active one"
  shell: |
    find {{ appshome }}/{{ app.name }}/releases -maxdepth 1 -name "20*" | sort -r | tail -n +6 |
    grep -v "$(readlink {{ appshome }}/{{ app.name }}/current)" | xargs rm -rf

- name: "symlinking current html app directory on {{ inventory_hostname }}"
  file:
    src: "{{ appshome }}/{{ app.name }}/releases/{{ releasenow }}"
    dest: "{{ appshome }}/{{ app.name }}/current"
    force: yes
    state: link

- name: populating server_names
  include_tasks: servernames.yml

- name: "creating/updating SSL certs for {{ app.name }}"
  when: usessl is defined and usessl|bool
  include_tasks: certs.yml

- name: "creating/updating nginx site configuration for {{ app.name }}"
  include_tasks: sites.yml

- name: reloading nginx
  when: nginx is defined
  service:
    name: nginx
    state: reloaded
