---
- name: "updating nginx (default) site definition"
  register: site3default
  when: nginx is defined
  template:
    src: nginx-default-site
    dest: "/etc/nginx/sites-available/default"
    mode: a+r

- name: removing default (enabled) nginx site
  when: nginx is defined
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: "enabling nginx default site"
  when: nginx is defined
  file:
    src: "/etc/nginx/sites-available/default"
    dest: "/etc/nginx/sites-enabled/00default"
    state: link
    force: yes

- name: "uploading nginx site definition for {{ app.name }}"
  register: site3upload
  when: nginx is defined
  template:
    src: nginx-html-site
    dest: "/etc/nginx/sites-available/{{ app.name }}"
    mode: a+r

- name: "enabling nginx site for {{ app.name }}"
  register: site3enable
  when: nginx is defined
  file:
    src: "/etc/nginx/sites-available/{{ app.name }}"
    dest: "/etc/nginx/sites-enabled/{{ app.name }}"
    state: link
    force: yes

- name: trigger nginx reloading
  set_fact: reload=true
  when: site3default is changed or site3upload is changed or site3enable is changed
